/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Pages;

import DBConnection.DbConnection;
import Methods.FetchData;
import Methods.SetColour;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
public class Home extends javax.swing.JFrame {
    
    SetColour sc = new SetColour();//call method folder setColour class
    
    FetchData fd = new FetchData(); //call method folder FetchData class
    
    ResultSet rs = null;
    Statement st = null;
    DbConnection con = null;
    
    public Home() {
        initComponents();
        
        // establishing connection
        con = new DbConnection();
        try {
            st = con.getConnection().createStatement();
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        this.setLocationRelativeTo(null); //center window
        
        fd.fillJTable(jTable1, "");
       
    }
    
    void retrieve_inbox() throws SQLException  // retrive request table
    {
        rs = st.executeQuery("select * from requests");
        jTable1.setModel(DbUtils.resultSetToTableModel(rs));
    }
    
    void retrieve_confirmed() throws SQLException // retrive confirmed table
    {
        rs = st.executeQuery("select name, location, bloodGroup, contact, date from confirmed where eligibility = 'Eligible' order by date");
        jTable2.setModel(DbUtils.resultSetToTableModel(rs));
    }
    
      void retrieve_rejected() throws SQLException // retrive rejected table
    {
        rs = st.executeQuery("select name, age, location, bloodGroup, contact from confirmed where eligibility = 'Not Eligible'");
        jTable6.setModel(DbUtils.resultSetToTableModel(rs));
    }
      
      void retrieve_completed() throws SQLException // retrive completed table
    {
        rs = st.executeQuery("select * from completed");
        jTable7.setModel(DbUtils.resultSetToTableModel(rs));
    }
      
       void retrieve_donors() throws SQLException // retrive donors table
    {
        rs = st.executeQuery("select name, location, bloodGroup, contact from completed order by name");
        jTable8.setModel(DbUtils.resultSetToTableModel(rs));
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_Inbox = new javax.swing.JLabel();
        jLabel_Confirmed = new javax.swing.JLabel();
        jLabel_Completed = new javax.swing.JLabel();
        jLabel_Rejected = new javax.swing.JLabel();
        jLabel_Donors = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel_Username = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextField_Search = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_Name = new javax.swing.JTextField();
        jTextField_Age = new javax.swing.JTextField();
        jTextField_Location = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField_BloodGrp = new javax.swing.JTextField();
        jTextField_Contact = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        btn_CancelInbox = new java.awt.Button();
        btn_ConfirmInbox = new java.awt.Button();
        btn_RefreshInbox = new java.awt.Button();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jTextField_NameCom = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField_LocationCom = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField_BloodGrpCom = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField_ContactCom = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        btn_UpdateConfirmPane = new java.awt.Button();
        btn_CancelConfirmPane = new java.awt.Button();
        btn_RefreshconfirmPane = new java.awt.Button();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTable7 = new javax.swing.JTable();
        button7 = new java.awt.Button();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable6 = new javax.swing.JTable();
        button6 = new java.awt.Button();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTable8 = new javax.swing.JTable();
        btn_RefreshDonors = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(33, 63, 86));

        jLabel_Inbox.setBackground(new java.awt.Color(22, 42, 57));
        jLabel_Inbox.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_Inbox.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Inbox.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Inbox.setText("Inbox");
        jLabel_Inbox.setToolTipText("Pending requests");
        jLabel_Inbox.setOpaque(true);
        jLabel_Inbox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_InboxMouseClicked(evt);
            }
        });

        jLabel_Confirmed.setBackground(new java.awt.Color(33, 63, 86));
        jLabel_Confirmed.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_Confirmed.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Confirmed.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Confirmed.setText("Confirmed Appointments");
        jLabel_Confirmed.setToolTipText("The list of confirmed appoinments");
        jLabel_Confirmed.setOpaque(true);
        jLabel_Confirmed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_ConfirmedMouseClicked(evt);
            }
        });

        jLabel_Completed.setBackground(new java.awt.Color(33, 63, 86));
        jLabel_Completed.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_Completed.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Completed.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Completed.setText("Completed");
        jLabel_Completed.setToolTipText("The list of completed appoinments");
        jLabel_Completed.setOpaque(true);
        jLabel_Completed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_CompletedMouseClicked(evt);
            }
        });

        jLabel_Rejected.setBackground(new java.awt.Color(33, 63, 86));
        jLabel_Rejected.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_Rejected.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Rejected.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Rejected.setText("Rejected Appointments");
        jLabel_Rejected.setToolTipText("The list of rejected appoinments");
        jLabel_Rejected.setOpaque(true);
        jLabel_Rejected.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_RejectedMouseClicked(evt);
            }
        });

        jLabel_Donors.setBackground(new java.awt.Color(33, 63, 86));
        jLabel_Donors.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel_Donors.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Donors.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Donors.setText("Our Donors");
        jLabel_Donors.setToolTipText("Details about the donors");
        jLabel_Donors.setOpaque(true);
        jLabel_Donors.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_DonorsMouseClicked(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Drop of Blood_80px.png"))); // NOI18N

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Pulse_96px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Inbox, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Confirmed, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Rejected, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Completed, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Donors, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jLabel_Inbox, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_Confirmed, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_Rejected, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_Completed, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_Donors, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(61, 92, 116));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Minimize Window_25px.png"))); // NOI18N
        jLabel9.setToolTipText("Minimize");
        jLabel9.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel9MousePressed(evt);
            }
        });

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Maximize Window_25px.png"))); // NOI18N
        jLabel10.setToolTipText("Maximize");
        jLabel10.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.setEnabled(false);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Close Window_25px.png"))); // NOI18N
        jLabel11.setToolTipText("Close");
        jLabel11.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel11MousePressed(evt);
            }
        });

        jLabel_Username.setFont(new java.awt.Font("Footlight MT Light", 1, 18)); // NOI18N
        jLabel_Username.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Username.setText("Welcome User");

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Exit_25px_1.png"))); // NOI18N
        jLabel22.setToolTipText("Sign out");
        jLabel22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });

        jTextField_Search.setBackground(new java.awt.Color(172, 204, 231));
        jTextField_Search.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTextField_Search.setForeground(new java.awt.Color(0, 0, 0));
        jTextField_Search.setToolTipText("Enter search value");
        jTextField_Search.setBorder(null);
        jTextField_Search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_SearchKeyReleased(evt);
            }
        });

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Search_25px_2.png"))); // NOI18N
        jLabel23.setToolTipText("Search");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Username, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(252, 252, 252))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_Username, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setLayout(new java.awt.CardLayout());

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Name");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Age");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Location");

        jTextField_Name.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTextField_Name.setEnabled(false);
        jTextField_Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_NameActionPerformed(evt);
            }
        });

        jTextField_Age.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTextField_Age.setEnabled(false);

        jTextField_Location.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTextField_Location.setEnabled(false);

        jTable1.setBackground(new java.awt.Color(204, 204, 204));
        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTable1.setForeground(new java.awt.Color(0, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Age", "Location", "Blood Group", "Contact"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setRowHeight(22);
        jTable1.setShowHorizontalLines(false);
        jTable1.setShowVerticalLines(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Blood Group");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Contact");

        jTextField_BloodGrp.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTextField_BloodGrp.setEnabled(false);

        jTextField_Contact.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTextField_Contact.setEnabled(false);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Eligibilty");

        jComboBox2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Eligible", "Not Eligible" }));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Date");

        btn_CancelInbox.setBackground(new java.awt.Color(204, 204, 204));
        btn_CancelInbox.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_CancelInbox.setLabel("Cancel");
        btn_CancelInbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancelInboxActionPerformed(evt);
            }
        });

        btn_ConfirmInbox.setBackground(new java.awt.Color(204, 204, 204));
        btn_ConfirmInbox.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_ConfirmInbox.setLabel("Confirm");
        btn_ConfirmInbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ConfirmInboxActionPerformed(evt);
            }
        });

        btn_RefreshInbox.setBackground(new java.awt.Color(204, 204, 204));
        btn_RefreshInbox.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_RefreshInbox.setLabel("Refresh");
        btn_RefreshInbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RefreshInboxActionPerformed(evt);
            }
        });

        jDateChooser1.setBackground(new java.awt.Color(204, 204, 204));
        jDateChooser1.setToolTipText("");
        jDateChooser1.setDateFormatString(" yyyy-MM-dd");
        jDateChooser1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextField_Location, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(jTextField_BloodGrp, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(jTextField_Contact, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(jTextField_Age, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(jTextField_Name, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(jComboBox2, 0, 130, Short.MAX_VALUE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(btn_CancelInbox, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_RefreshInbox, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_ConfirmInbox, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Location, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_BloodGrp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Contact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_CancelInbox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_ConfirmInbox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_RefreshInbox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(88, 88, 88))
        );

        jPanel3.add(jPanel4, "card2");

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));

        jTable2.setBackground(new java.awt.Color(204, 204, 204));
        jTable2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jTable2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTable2.setForeground(new java.awt.Color(0, 0, 0));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Location", "Blood Group", "Contact", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setGridColor(new java.awt.Color(255, 255, 255));
        jTable2.setRowHeight(22);
        jTable2.setShowHorizontalLines(false);
        jTable2.setShowVerticalLines(false);
        jTable2.getTableHeader().setReorderingAllowed(false);
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Name");

        jTextField_NameCom.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTextField_NameCom.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Location");

        jTextField_LocationCom.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTextField_LocationCom.setEnabled(false);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Blood Group");

        jTextField_BloodGrpCom.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTextField_BloodGrpCom.setEnabled(false);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Contact");

        jTextField_ContactCom.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTextField_ContactCom.setEnabled(false);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Status");

        jCheckBox1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckBox1.setText("Complete");

        btn_UpdateConfirmPane.setBackground(new java.awt.Color(204, 204, 204));
        btn_UpdateConfirmPane.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_UpdateConfirmPane.setLabel("Update");
        btn_UpdateConfirmPane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UpdateConfirmPaneActionPerformed(evt);
            }
        });

        btn_CancelConfirmPane.setBackground(new java.awt.Color(204, 204, 204));
        btn_CancelConfirmPane.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_CancelConfirmPane.setLabel("Cancel");
        btn_CancelConfirmPane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancelConfirmPaneActionPerformed(evt);
            }
        });

        btn_RefreshconfirmPane.setBackground(new java.awt.Color(204, 204, 204));
        btn_RefreshconfirmPane.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_RefreshconfirmPane.setLabel("Refresh");
        btn_RefreshconfirmPane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RefreshconfirmPaneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jTextField_NameCom, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField_LocationCom, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                    .addComponent(jTextField_BloodGrpCom, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                    .addComponent(jTextField_ContactCom, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                    .addComponent(jCheckBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(btn_CancelConfirmPane, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_UpdateConfirmPane, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                        .addGap(25, 25, 25))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(btn_RefreshconfirmPane, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_NameCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_LocationCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_BloodGrpCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_ContactCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox1))))
                .addGap(45, 45, 45)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_UpdateConfirmPane, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(btn_CancelConfirmPane, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(btn_RefreshconfirmPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel5, "card3");

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));

        jTable7.setBackground(new java.awt.Color(204, 204, 204));
        jTable7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jTable7.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTable7.setForeground(new java.awt.Color(0, 0, 0));
        jTable7.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Age", "Location", "Blood Group", "Contact"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable7.setGridColor(new java.awt.Color(255, 255, 255));
        jTable7.setRowHeight(22);
        jTable7.setShowHorizontalLines(false);
        jTable7.setShowVerticalLines(false);
        jTable7.getTableHeader().setReorderingAllowed(false);
        jScrollPane8.setViewportView(jTable7);

        button7.setBackground(new java.awt.Color(204, 204, 204));
        button7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        button7.setLabel("Refresh");
        button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 769, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(321, 321, 321)
                .addComponent(button7, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(button7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel6, "card4");

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));

        jTable6.setBackground(new java.awt.Color(204, 204, 204));
        jTable6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jTable6.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTable6.setForeground(new java.awt.Color(0, 0, 0));
        jTable6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Age", "Location", "Blood Group", "Contact"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable6.setGridColor(new java.awt.Color(255, 255, 255));
        jTable6.setRowHeight(22);
        jTable6.setShowHorizontalLines(false);
        jTable6.setShowVerticalLines(false);
        jTable6.getTableHeader().setReorderingAllowed(false);
        jScrollPane7.setViewportView(jTable6);

        button6.setBackground(new java.awt.Color(204, 204, 204));
        button6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        button6.setLabel("Refresh");
        button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 769, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(321, 321, 321)
                .addComponent(button6, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(button6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel7, "card5");

        jPanel8.setBackground(new java.awt.Color(204, 204, 204));

        jTable8.setBackground(new java.awt.Color(204, 204, 204));
        jTable8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jTable8.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTable8.setForeground(new java.awt.Color(0, 0, 0));
        jTable8.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Location", "Blood Group", "Contact"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable8.setGridColor(new java.awt.Color(255, 255, 255));
        jTable8.setRowHeight(22);
        jTable8.setShowHorizontalLines(false);
        jTable8.setShowVerticalLines(false);
        jTable8.getTableHeader().setReorderingAllowed(false);
        jScrollPane9.setViewportView(jTable8);

        btn_RefreshDonors.setBackground(new java.awt.Color(204, 204, 204));
        btn_RefreshDonors.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_RefreshDonors.setLabel("Refresh");
        btn_RefreshDonors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RefreshDonorsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 769, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(321, 321, 321)
                        .addComponent(btn_RefreshDonors, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btn_RefreshDonors, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel8, "card6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_InboxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_InboxMouseClicked

        // set color methods for the menu labels
        sc.setColour(jLabel_Inbox);
        sc.resetColour(jLabel_Confirmed );
        sc.resetColour(jLabel_Rejected );
        sc.resetColour(jLabel_Completed );
        sc.resetColour(jLabel_Donors );
        
        // displaying panels on mouse click
        jPanel3.removeAll();
        jPanel3.add(jPanel4);
        jPanel3.repaint();
        jPanel3.revalidate();
        
        // clearing text fields and other fields on panel load 
        jTextField_Name.setText("");
        jTextField_Age.setText("");
        jTextField_Location.setText("");
        jTextField_BloodGrp.setText("");
        jTextField_Contact.setText("");
        jTextField_Search.setText("");
        jDateChooser1.setDate(null);
        jComboBox2.setSelectedItem("Eligible");
        
        // retriving request table on panel load
        try {
            retrieve_inbox();
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }

       

    }//GEN-LAST:event_jLabel_InboxMouseClicked

    private void jLabel_ConfirmedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ConfirmedMouseClicked

        // set color methods for the menu labels
        sc.setColour(jLabel_Confirmed);
        sc.resetColour(jLabel_Inbox );
        sc.resetColour(jLabel_Rejected );
        sc.resetColour(jLabel_Completed );
        sc.resetColour(jLabel_Donors );
        
        // displaying panels on mouse click
        jPanel3.removeAll();
        jPanel3.add(jPanel5);
        jPanel3.repaint();
        jPanel3.revalidate();
        
        // clearing text fields and other fields on panel load 
        jTextField_NameCom.setText("");
        jTextField_LocationCom.setText("");
        jTextField_BloodGrpCom.setText("");
        jTextField_ContactCom.setText("");
        jCheckBox1.setSelected(false);
        
        // retriving confirmed table on panel load
        try {
            retrieve_confirmed();
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jLabel_ConfirmedMouseClicked

    
    private void jLabel_CompletedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CompletedMouseClicked

        // set color methods for the menu labels
        sc.setColour(jLabel_Completed);
        sc.resetColour(jLabel_Confirmed );
        sc.resetColour(jLabel_Rejected );
        sc.resetColour(jLabel_Inbox );
        sc.resetColour(jLabel_Donors );

        // displaying panels on mouse click
        jPanel3.removeAll();
        jPanel3.add(jPanel6);
        jPanel3.repaint();
        jPanel3.revalidate();
        
        // retriving completed table on panel load
        try {
            retrieve_completed();
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        

    }//GEN-LAST:event_jLabel_CompletedMouseClicked

    private void jLabel_RejectedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_RejectedMouseClicked

        // set color methods for the menu labels
        sc.setColour(jLabel_Rejected);
        sc.resetColour(jLabel_Inbox);
        sc.resetColour(jLabel_Confirmed );
        sc.resetColour(jLabel_Completed );
        sc.resetColour(jLabel_Donors );

        // displaying panels on mouse click
        jPanel3.removeAll();
        jPanel3.add(jPanel7);
        jPanel3.repaint();
        jPanel3.revalidate();
        
        // retriving rejected table on panel load
        try {
            retrieve_rejected();
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jLabel_RejectedMouseClicked

    private void jLabel_DonorsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_DonorsMouseClicked

        // set color methods for the menu labels
        sc.setColour(jLabel_Donors);
        sc.resetColour(jLabel_Confirmed );
        sc.resetColour(jLabel_Rejected );
        sc.resetColour(jLabel_Completed );
        sc.resetColour(jLabel_Inbox );
        
        // displaying panels on mouse click
        jPanel3.removeAll();
        jPanel3.add(jPanel8);
        jPanel3.repaint();
        jPanel3.revalidate();
        
        // retriving donors table on panel load
        try {
            retrieve_donors();
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jLabel_DonorsMouseClicked

    private void jLabel9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MousePressed

        this.setState(JFrame.ICONIFIED);//minimize 

    }//GEN-LAST:event_jLabel9MousePressed

    private void jLabel11MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MousePressed

        System.exit(WIDTH);//Close Programme
    }//GEN-LAST:event_jLabel11MousePressed

    int xx, xy; // variables for dragging the pane
    
    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        
        // drag the pane with mouse
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx, y-xy);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
       
        //drag the pane with mouse
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        
        // sign out
        LoginForm ln = new LoginForm();
        ln.setVisible(true);
        this.dispose();
                   
    }//GEN-LAST:event_jLabel22MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        
        // get selected row to the text fields on cell click
        int rowIndex = jTable1.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        jTextField_Name.setText(model.getValueAt(rowIndex,0).toString());
        jTextField_Age.setText(model.getValueAt(rowIndex,1).toString());
        jTextField_Location.setText(model.getValueAt(rowIndex,2).toString());
        jTextField_BloodGrp.setText(model.getValueAt(rowIndex,3).toString());
        jTextField_Contact.setText(model.getValueAt(rowIndex,4).toString());
        
    }//GEN-LAST:event_jTable1MouseClicked

    
    public boolean verifText()
    {
        // checking if a record is selected
        if (jTextField_Name.getText().equals("")) 
        {
            JOptionPane.showMessageDialog(null, "Please select a request");
            return false;
        }
        // updating the table if combo box value is Not Eligible
        else if (jComboBox2.getSelectedItem() == "Not Eligible" ) 
        {
        String name = jTextField_Name.getText();
        String age = jTextField_Age.getText();
        String location = jTextField_Location.getText();
        String bloodGrp = jTextField_BloodGrp.getText();
        String contact  = jTextField_Contact.getText();
        String date = null;
        String eligibility = jComboBox2.getSelectedItem().toString();
        
        // updating the table as not eligible and displaying message as Denied
        FetchData fd = new FetchData ();
            fd.Insert('i', name, age, location, bloodGrp, contact, date, eligibility);
            JOptionPane.showMessageDialog(null, "Appointment request denied");
            
            //deleting record from requests table after the appointment is confirmed on confirm button click
            fd.Delete('d', name, null, null, null, null);
            
        // clearing text fields and other fields after button click   
        jTextField_Name.setText("");
        jTextField_Age.setText("");
        jTextField_Location.setText("");
        jTextField_BloodGrp.setText("");
        jTextField_Contact.setText("");
        jDateChooser1.setDate(null);
        
        // retrieving request table after updating not eligible
        try {
            retrieve_inbox();
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        
            return true;
        }
        
        // checking whether a date is assigned if Eligible
        else if(jComboBox2.getSelectedItem() == "Eligible" && jDateChooser1.getDate() == null)
        {
            JOptionPane.showMessageDialog(null,"Please pick a date.");
            return false;
        }
        //choose a date higher than the current date
        else if (jDateChooser1.getDate().compareTo(new Date())<0)
        {
            JOptionPane.showMessageDialog(null,"Please pick a date ahead of the current date.");
            return false;
        }
        
        else
        {
            return true;
        }
    }
    
    
    private void btn_ConfirmInboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ConfirmInboxActionPerformed
        
        
        // variable declaration and assigning fields for inserting into table
        String name = jTextField_Name.getText();
        String age = jTextField_Age.getText();
        String location = jTextField_Location.getText();
        String bloodGrp = jTextField_BloodGrp.getText();
        String contact  = jTextField_Contact.getText();
        String eligibility = jComboBox2.getSelectedItem().toString();
        
        // executes when verifText method is true 
        if (verifText())
        {
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String date = dateFormat.format(jDateChooser1.getDate()); // assigining the date to a string variable
        
            // inserting data into confirmed table
            FetchData fd = new FetchData ();
            fd.Insert('i', name, age, location, bloodGrp, contact, date, eligibility);
            JOptionPane.showMessageDialog(null, "Appointment confirmed");
            
            //deleting record from requests table after the appointment is confirmed on confirm button click
            fd.Delete('d', name, null, null, null, null);
            
        // clearing text fields after inserting data on confirm button clicked
        jTextField_Name.setText("");
        jTextField_Age.setText("");
        jTextField_Location.setText("");
        jTextField_BloodGrp.setText("");
        jTextField_Contact.setText("");
        jDateChooser1.setDate(null);
        jComboBox2.setSelectedItem("Eligible");
        
        // retrieving request table after confirm button clicked
        try {
            retrieve_inbox();
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        }
      
    }//GEN-LAST:event_btn_ConfirmInboxActionPerformed

    private void btn_RefreshconfirmPaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RefreshconfirmPaneActionPerformed

        // clearing text fields on refresh button clicked
        jTextField_NameCom.setText("");
        jTextField_LocationCom.setText("");
        jTextField_BloodGrpCom.setText("");
        jTextField_ContactCom.setText("");
        jCheckBox1.setSelected(false);
        
        // retrieving confirmed table when refresh button clicked
        try {
            retrieve_confirmed();
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btn_RefreshconfirmPaneActionPerformed

    private void button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button7ActionPerformed
        
        // retrieving completed table when refresh button clicked
        try {
            retrieve_completed();
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_button7ActionPerformed

    private void button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button6ActionPerformed
        
        // retrieving rejected table when refresh button clicked
        try {
            retrieve_rejected();
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_button6ActionPerformed

    private void btn_UpdateConfirmPaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UpdateConfirmPaneActionPerformed
        
        // variables for updating table completed
        String name = jTextField_NameCom.getText();
        String location = jTextField_LocationCom.getText();
        String bloodGrp = jTextField_BloodGrpCom.getText();
        String contact  = jTextField_ContactCom.getText();
        String status = "Completed";
        
        
        // checking if a record is selected
        if (jTextField_NameCom.getText().equals("")) 
        {
            JOptionPane.showMessageDialog(null, "Please select an Appoinment to mark as Completed.");
            
        }
        // checkiong whether the checkbox is selected or not
        else if(jCheckBox1.isSelected() == false)
        {
            JOptionPane.showMessageDialog(null,"Please indicate whether the Appointment is completed or not.");
        }
        else
        {
            // updating completed table
            FetchData fd = new FetchData ();
            fd.Update('u', name, location, bloodGrp, contact, status);
            
            //deleting record from confirmed table after the appointment is completed on update button click
            fd.Delete2('c', name, null, null, null, null);
          
        // clearing text fields after updating 
        jTextField_NameCom.setText("");
        jTextField_LocationCom.setText("");
        jTextField_BloodGrpCom.setText("");
        jTextField_ContactCom.setText("");
        jCheckBox1.setSelected(false);
        
        // retrieving confirmed table after updating
            try {
                retrieve_confirmed();
            } catch (SQLException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }
        
        
        
    }//GEN-LAST:event_btn_UpdateConfirmPaneActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        
        // get selected row to the text fields on cell click
        int rowIndex = jTable2.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        jTextField_NameCom.setText(model.getValueAt(rowIndex,0).toString());
        jTextField_LocationCom.setText(model.getValueAt(rowIndex,1).toString());
        jTextField_BloodGrpCom.setText(model.getValueAt(rowIndex,2).toString());
        jTextField_ContactCom.setText(model.getValueAt(rowIndex,3).toString());
        
    }//GEN-LAST:event_jTable2MouseClicked

    private void btn_RefreshDonorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RefreshDonorsActionPerformed
        
        // retrieving Donors table on refresh button click
        try {
            retrieve_donors();
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_RefreshDonorsActionPerformed

    private void btn_CancelConfirmPaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelConfirmPaneActionPerformed
        
        // clearing text fields on cancel button click
        jTextField_NameCom.setText("");
        jTextField_LocationCom.setText("");
        jTextField_BloodGrpCom.setText("");
        jTextField_ContactCom.setText("");
        jCheckBox1.setSelected(false);
        
        // retrieving confirmed table on cancel button click
        try {
            retrieve_confirmed();
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btn_CancelConfirmPaneActionPerformed

    private void btn_CancelInboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelInboxActionPerformed
        
        // retrieving inbox on cancel button click
        try {
            retrieve_inbox();
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        // clearing text fields on cancel button click
        jTextField_Name.setText("");
        jTextField_Age.setText("");
        jTextField_Location.setText("");
        jTextField_BloodGrp.setText("");
        jTextField_Contact.setText("");
        jTextField_Search.setText("");
        jDateChooser1.setDate(null);
        jComboBox2.setSelectedItem("Eligible");
    }//GEN-LAST:event_btn_CancelInboxActionPerformed

    private void btn_RefreshInboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RefreshInboxActionPerformed

        // retrieving inbox on refresh button click
        try {
            retrieve_inbox();
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        // clearing text fields on refresh button click
        jTextField_Name.setText("");
        jTextField_Age.setText("");
        jTextField_Location.setText("");
        jTextField_BloodGrp.setText("");
        jTextField_Contact.setText("");
        jTextField_Search.setText("");
        jDateChooser1.setDate(null);
        jComboBox2.setSelectedItem("Eligible");
        
    }//GEN-LAST:event_btn_RefreshInboxActionPerformed

    private void jTextField_NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_NameActionPerformed

    private void jTextField_SearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_SearchKeyReleased
        
        jTable1.setModel(new DefaultTableModel(null, new Object[]{"Name","Age","Location", "BloodGrp","Contact"}));
        fd.fillJTable(jTable1, jTextField_Search.getText());
        
    }//GEN-LAST:event_jTextField_SearchKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btn_CancelConfirmPane;
    private java.awt.Button btn_CancelInbox;
    private java.awt.Button btn_ConfirmInbox;
    private java.awt.Button btn_RefreshDonors;
    private java.awt.Button btn_RefreshInbox;
    private java.awt.Button btn_RefreshconfirmPane;
    private java.awt.Button btn_UpdateConfirmPane;
    private java.awt.Button button6;
    private java.awt.Button button7;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_Completed;
    private javax.swing.JLabel jLabel_Confirmed;
    private javax.swing.JLabel jLabel_Donors;
    private javax.swing.JLabel jLabel_Inbox;
    private javax.swing.JLabel jLabel_Rejected;
    public static javax.swing.JLabel jLabel_Username;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    public static javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable6;
    private javax.swing.JTable jTable7;
    private javax.swing.JTable jTable8;
    private javax.swing.JTextField jTextField_Age;
    private javax.swing.JTextField jTextField_BloodGrp;
    private javax.swing.JTextField jTextField_BloodGrpCom;
    private javax.swing.JTextField jTextField_Contact;
    private javax.swing.JTextField jTextField_ContactCom;
    private javax.swing.JTextField jTextField_Location;
    private javax.swing.JTextField jTextField_LocationCom;
    private javax.swing.JTextField jTextField_Name;
    private javax.swing.JTextField jTextField_NameCom;
    private javax.swing.JTextField jTextField_Search;
    // End of variables declaration//GEN-END:variables
}
